<?php 
#!/usr/local/bin/php
$spells=array(
'ice wind',
'breath taker',
'poison wind',
'disco inferno',
'lightning blast',
'stone crusher',
'ice wind',
'acid storm',
'poison storm',
'fire storm',
'lightning storm' ,
'thunder storm',
'dead fog',
'flesh melt',
'inner confusion',
'bone cracker',
'mind eraser',
'blood burn',
'spell of spirits touch',
'poison wind',
'frozen blast',
'mindblow',
'parallux nexus',
'mind warp',
'ether sting',
'bone chill',
'brain xplosions',
'hart damage',
'demons hand',
'mind stalker',
'brain storm',
'giant worms',
'poisoned claw',
'blood tears',
'lighting arobj',
'stone giant',
'arcane terror',
'hell spirit',
'bone frost' ,
'needles eye',
'damned spectre',
'chill thrill',
'crazy vengeance',
'doomed first lady',
'burning longs',
'vulcan corruptions',
'space asteroids',
'faces of walls',
'turn inside out' ,
'muscle melted',
'demons separated',
'cupido from hell',
'frozen orb',
'shock of the damned',
'guided lightning',
'brain shake','mesa asteroids rain',
'wall of eyeless',
'moleculaire fader',
'weaken enemy',
'fire ghost',
'frost waterfall',
'poison ocean',
'rock blast',
'iron maiden',
'dual lightning charges',
'great fireballs',
'fire wall',
'poison damp',
'chain lightning',
'wall of frost',
'inferno blast',
'lightning wall',
'fireball storm',
'poison tornado',
'bone spirit',
'stone flesh',
'lightning clouds',
'thunder tornado',
'nonstop bleeding',
'sweet blood',
'brain splat',
'blood boil',
'hell blast',
'wak ana tokoyo',
'chaos ghost of lightning',
'instant pregnant',
'moon drop',
'arctic annihilate freeze',
'lava dump',
'skeleton takeover',
'mind disaster',
'blind poison',
'long xplode',
'hart sting',
'multiple mesa sun beam',
'spirit of elements',
'evil flesh ghost',
'chain lightning wave',
'terror drone',
'elemental blood suck',
'mind kill',
'muscle disorder',
'rock freeze',
'brain meltdown',
'stonage spirit',
'head piercing',
'teleport to outer space',
'molecular vanish',
'shadow eraser',
'send back to history',
'future travel',
'dino crush',
'flesh corruption',
'forsaken death',
'return to birth',
'ten months pregnant',
'timer eraser',
'eternal lifetaker',
'darkstorm of hands',
'shintelo seperator',
'fast bone melt',
'arse is on fire',
'doomed devastator',
'soul danger',
'soul burner',
'hart xplosions',
'blood burst',
'blood exchange',
'skull takeway',
'dragon rain',
'fast bone gobj',
'blood vanish',
'mind eraser',
'spirit of anarchy',
'shadow drain of life',
'intelernal life taker',
'teleport to underground',
'brain vaporise',
'wall of the banshee',
'evil giant undead critters',
'doomed acid fog',
'poisoned lava storm',
'fast skin removal',
'instant blood stop',
'doomed reepers hand',
'column of enternal fire',
'brain implode',
'big maelstrom',
'evil gang bang',
'vaporisor flash',
'doomed destiny',
'memory erase',
'evil dead plague',
'doomed showclouds',
'xperience undertaker',
'soul killer',
'soul vanish',
'summon warlord',
'molecular disassemble',
'atomic dismantle',
'atomic disruptor'
);
?>