<tr><th align="center" colspan="2">Races</th></tr>
<tr>
<td>[1,2,3,4]</td><td>1=attack power(attack damage with weapon),<br>2=defend power(decrease and block incoming damages),<br>3=mystical power(casting attackspell and healspell),<br>4=thief power(multifier for experience and gold stealing in a battle).<br>Thanks to Santiago for the longer race DESCriptions.</td>
</tr>

<?php 
#!/usr/local/bin/php

$races_des=array(
'Alfs'=>"A race of small furry creatures. most look down on members of this race for their small size and their lack of specialization. The Alfs society Contraventionains of strengthong individuals which are quick to take whatever they can get their hands on,including knowledge. This has made the Alfs Intelligenceo perfect thieves,with their small constitution they can easily get Intelligenceo places unseen,they also have a knack for finding gold however good it is hidden.",
'Asumodus'=>"Hailing from the waist deserts this nomadic species has hardened and become fierce warriors. most of the Asumodus loathes magic claiming that the sword is all you need to kill someone. Even so the Asumodus has decent natural magic defense and some have been known to use a kind of shamanistic offspring of magic.",
'Barbarian'=>"Being an offspring of the Human race the Barbarians has been living in isolated areas of the world. mountain ranges and deserts are known to house these warriors. Having specialized in battle for centuries they have lost most of the magic powers the Human race possess. in exchange they have gained great knowledge in attacking and defending with a great arsenal of weapons. Unafraid of the dangers of battles many Barbarians has been known to become berserks with little Concentrationern for their own safety.",
'Beasties'=>"Living deep in the dark dense forests the Beasties has reached a great understanding of the animal life and the need for balance in the world. They use their LIMITed magic ability to communicate with animals. In exchange for protecting the forests the Beasties gets aid from the animals when fighting and looting their enemies. Their ability to summon animals in battle has made them feared warriors all over the world and one should think twice before penetrating the dark forests they protect.",
'Dracoids'=>"A distant relative to the mighty dragons. Without the great stature and strength of their grander relatives the Dracoids rely solely on their magic powers in combat,with hard scales covering their bodies as a second armor. Their main weak poIntelligences are their slow learning curve and their lack of Intelligenceerest in gold. A Dracoid typically gain strength slowly but is a formidable foe for anyone who isn't cautious.",
'Drow'=>"A long time ago a great war raged amongst the elves. As a result of the battle the losers was banished from the light and forced to live in the underground caves known as Underdark. Living in these caves for a long time has turned the one-time elves Intelligenceo dark creatures who are sworn enemies of the elves. The years that has past the Drow has used to perfect their magic and defensive skills to make sure that they will never fail again.",
'Dwarf'=>"Small but sturdy,the rough dwarves lives for the sound of steel against steel and the sound of gold in the purse. Their lack for size and mystical aptitude they make up with determination. Anyone stupid enough calling these creatures small while they are listening should make sure they are well armored or they will lose a leg or two.",
'Elves'=>"By the appearance of the Elves one would think they were a close relative to the humans but even though their looks are similar these forest dwellers are fundamentally different from the humans not only in society and belief. The Elves has a long lifespan and are often hated by the short lived humans,they also possess a great mystical potential. Although many of their kind has some kind of mystical skill there are also many who specializes in warfare spreading terror on the battlefield.",
'Eurodite'=>"Creatures of great mystical aptitude who live high in the mountains. Being solitary creatures they seldom wander beyond the mountain ranges in which they dwell. Sharing their territories with the savage Barbarians the Eurodites has perfected their mystical abilities,while still being capable of basic combat,to defend themselves against the danger.",
'Faeries'=>"Being mischievous creators by nature the Faeries roam the countryside giving creatures they meet 3 wishes to spend,beware however,if they can't fulfill your promise they will take your life. Their tiny size makes them hard to hit while their mystical blasts is lethal to most mortals,this makes them a formidable enemy in combat.",
'Gnome'=>"Formerly a race of great inventors,but having their caves constantly overrun with Goblins and Ogres have driven these dwarf-like creatures to harden Intelligenceo a warrior race. Unfortunately much of their knowledge about the ancient mystics were lost in the generations of war.",
'Goblins'=>"The Goblins are despised and feared amongst most civilized races in the world. Their though green skin and tall stature means plunder and death to many villages. Goblins are slow learners and their minds are so set on killing and mutilating that they usually don't care what they gain from it.",
'Human'=>"The most common race of the world,the Humans features adventurers of all kinds. The experienceloitation and experienceansion of the Human empires often drives them Intelligenceo confrontation with several of the other races,especially their habit of using wood to build their dwellings had led them Intelligenceo confrontation with elves and Beasties.",
'Humeves'=>"The result of bonding between Humans and Elves has led to this subspecies. The Humeves is despised by both the Humans and Elves and see as 'un pure',this has led the Humeves Intelligenceo a life of adventure and experienceloration searching for places WHERE they are accepted for what they are. They have inherited the mystical capabilities from the Elves while the union has led to a weakening of their strength.",
'Hydroids'=>"The Hydroids absorbs the free magic in the air through their skin,which causes a faIntelligence glow that can be seen at night. They use this magic as energy source and have no need to eat. The tradeoff for using magic as energy source is that their endurance would decrease heavily if they were to use any major magic. The Hydroids makes up for this through the strength they gain from the energy,and after killing an enemy they sap the remaining magic energies from the body thereby sapping a portion of the enemies knowledge.",
'Ogre'=>"One of the largest Intelligenceelligent creatures there is. These large omnivorous eat anything from trees to humans,as long as it is edible they go for it. Their self-preservation drives them to eating whatever can't resist too much but if provoked or in great hunger they will attack anything. They might not have the strength to match their size but they are still amongst the strengthongest of the warrior races.",
'Ishae'=>"Beautiful agile women from the darkest place in the jungle to survive on hunting skills. Kill only what they need and stay harmony with the nature to get the most benefits from it.",
'Paladin'=>"The Paladins are Humans who at an early age is recognized as blessed by the gods. They are brought up as warriors but with great knowledge of magic,the power of the heals gets a boost from the deity of the Paladin and is known to cause either great destrengthuction or giving great aid in combat.",
'Reptasar'=>"Dwelling in the dark marshlands,where 'survival of the fittest' is the law,these reptiles has gained great endurance. they often rely on their thick scales and strengthong armor to defend them while they chant their heals in combat. As the Reptasar feels no qualm about devouring the cattle housed by the Humans these creatures have lately been hunted down by Humans living near marshlands,therefore the Reptasar has gobjn few in digits and has become extinct in several areas.",
'Necro'=>"With an army of skeletons they do not tolerate any resistance. Living with dead people has it price in loneliness and darkness, you will not see a necro laugh about a joke.",
'Sacro'=>"By sacrificing their foes to the deities they serve the Sacromancers has been granted great mystical powers and is feared in the field of battle. Aside from gaining great offensive magic they coat their armors with the blood of their enemies further increasing the effectiveness of their protection.",
'Troll'=>"Without doubt the strengthongest race of them all. Their offensive might is unequaled and if someone survives an encounter with a Troll they are either severely injured or incredibly fast. Aside from their physical might the Trolls are also gifted with a great resistance against magic. They seldom pursue their magic powers further then to defense but when they do they can rival the best mages. The great weakness of the Troll is the many weak poIntelligences in its defenses. They fear fire and they have several soft spots in their otherwise though skin.",
'Undead'=>"The Undead is not a race as much as it is a condition. The Undead keeps the shape of its former life but the mind is reshaped to a poIntelligence WHERE most of the memory and knowledge is lost. Gone is also all self preservation and fear making it the perfect killing machine. How do you kill something really isn't alive? The answer is simple: With great care. The weak poIntelligence of the undead is that they are very vulnerable for magic attacks as their minds are deeply regressed from the state of death.",
"Centaurs"=>"Centaurs are one of the most reclusive beings in the world tending to keep to the forests rather than mingling in open areas among Humans and other two legged beings. They are quite attune with nature as are Elves,and develop bonds with nature. Never will a Centaur take more than they needs from the land,if forced to,for instance cut down a tree.",
"Minotaurs"=>"Among the largest bipedal creatures is the minotaur,topping over eight feet with horns cresting out of the sides of it's skull. The minotaurs are as large as Ogres and allot strengthonger,in truth they are a little bit shorter and a bit more hardier. Usually bobjn,black or red colors the hide of the minotaur,while their horns range from light bobjn to black.",
"Satyrs"=>"Satyrs along with Centaurs live in the forests of the land. They are pleasure seekers and are primarily Intelligenceerested in fun things. Satyrs are very care free creatures and are entirely a male only species,their counterparts are believed to be Dryads which are an all female species. These goat-mens do not wander far from their home and are only offensive towards others Intelligenceruders",
"Wemics"=>"Wemics,another race of half beast half man heritage like minotaurs and Centaurs. Wemics though are half lion and half man beings that live more on their beast side. Their body is of a lion and their upper torso like Centaurs is humanoid.",
"Dragon"=>"They are small winged reptile like creatures from an unknown world that look like miniature dragons. They have a slightly more solid build than full sized dragons and they can be Blue,Grey,Green,or White in color. Even though they have a life span of 400 years,they mature in about two years. As many types of dragons can take a humanoid stance so can Dragons and their for forward feet can be used as hands with 60% of the ability of human hand. The creatures is Sentient and have a spoken language that can be understood with enough listening but can't be spoken by a person. This language is instinctively know by all members of the species. They also can understand after some listening,most other creatures tongues although they do not have the vocals to speak those those languages either. They are quite adept at learning human body language and can easily be understood using the Tongues heal. They form mated pairs on their home planet and that pair will normally work with one or two other mated pairs. This complex bonding often means that when not with their species,they will form emotional bonds with humans and other races and remain very loyal to them.",
);

require_once('AdMiN/array.races.php');
ksort($races_array);
foreach($races_array as $key=>$value){
?><tr<?php if(empty($bg)){?> bgcolor="<?php print $col_th;$bg=1;?>"<?php }else{$bg='';}?>><td><?php print $key;?></td><td>[<?php print "$value[0],$value[1],$value[2],$value[3]";?>]<br><?php print $races_des[$key];?></td></tr><?php 
}
?>